import { DomPurify } from '@/components/dom-purify';
import { SanitizeHtml } from '@/components/sanitize-html';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ backgroundColor: 'white', color: 'black', paddingLeft: 50 }}
      >
        {/* 
          NOTE: 
          <a href=javascript:alert('xss')>リンクをクリック</a>
          を埋め込むとXSS成功する 
        */}
        {/*
          NOTE: sanitize-htmlのサンプル
          const html = "<strong>hello world</strong>";
          console.log(sanitizeHtml(html));
          console.log(sanitizeHtml("<img src=x onerror=alert('img') />"));
          console.log(sanitizeHtml("console.log('hello world')"));
          console.log(sanitizeHtml("<script>alert('hello world')</script>")); 
        */}
        <div style={{ paddingTop: 100 }}></div>
        <p>SanitizeHtml</p>
        <SanitizeHtml />
        <div style={{ paddingTop: 100 }}></div>
        <p>DomPurify</p>
        <DomPurify />
        <div style={{ paddingTop: 100 }}></div>
      </main>
    </>
  );
}
